export interface Secteur {
  slug: string;
  icon: string;
  color: string;
  useCases: string[];
  stats: { value: string; label: Record<string, string> }[];
}

export interface SecteurTranslation {
  name: string;
  title: string;
  metaTitle: string;
  metaDescription: string;
  subtitle: string;
  useCases: string[];
  painPoint: string;
  solution: string;
  ctaText: string;
}

export const SECTEURS: Secteur[] = [
  {
    slug: "immobilier",
    icon: "🏠",
    color: "#25D366",
    useCases: ["qualification-leads", "prise-de-rdv", "relance-prospects"],
    stats: [
      { value: "340%", label: { fr: "plus de visites qualifiées", en: "more qualified visits", de: "mehr qualifizierte Besichtigungen" } },
      { value: "3min", label: { fr: "temps de réponse moyen", en: "average response time", de: "durchschnittliche Antwortzeit" } },
      { value: "-78%", label: { fr: "coût de qualification", en: "qualification cost", de: "Qualifizierungskosten" } },
    ],
  },
  {
    slug: "ecommerce",
    icon: "🛒",
    color: "#25D366",
    useCases: ["panier-abandonne", "suivi-commande", "service-client"],
    stats: [
      { value: "26%", label: { fr: "paniers récupérés", en: "carts recovered", de: "wiederhergestellte Warenkörbe" } },
      { value: "-62%", label: { fr: "coûts support", en: "support costs", de: "Supportkosten" } },
      { value: "98%", label: { fr: "taux d'ouverture", en: "open rate", de: "Öffnungsrate" } },
    ],
  },
  {
    slug: "sante",
    icon: "🏥",
    color: "#25D366",
    useCases: ["prise-de-rdv", "rappels-patients", "pre-admission"],
    stats: [
      { value: "-61%", label: { fr: "taux de no-show", en: "no-show rate reduction", de: "No-Show-Reduzierung" } },
      { value: "24/7", label: { fr: "disponibilité agenda", en: "booking availability", de: "Buchungsverfügbarkeit" } },
      { value: "94%", label: { fr: "satisfaction patients", en: "patient satisfaction", de: "Patientenzufriedenheit" } },
    ],
  },
  {
    slug: "restaurant",
    icon: "🍽️",
    color: "#25D366",
    useCases: ["reservations", "commandes-click-collect", "fidelisation"],
    stats: [
      { value: "+43%", label: { fr: "réservations directes", en: "direct reservations", de: "Direktreservierungen" } },
      { value: "-0%", label: { fr: "commissions plateforme", en: "platform commissions", de: "Plattformprovisionen" } },
      { value: "31%", label: { fr: "clients réactivés", en: "reactivated customers", de: "reaktivierte Kunden" } },
    ],
  },
  {
    slug: "assurance",
    icon: "🛡️",
    color: "#25D366",
    useCases: ["devis-automatiques", "gestion-sinistres", "renouvellement"],
    stats: [
      { value: "5min", label: { fr: "devis généré", en: "quote generated", de: "Angebot erstellt" } },
      { value: "+38%", label: { fr: "taux de conversion", en: "conversion rate", de: "Konversionsrate" } },
      { value: "-55%", label: { fr: "coût traitement sinistre", en: "claim processing cost", de: "Schadenbearbeitungskosten" } },
    ],
  },
  {
    slug: "btp",
    icon: "🏗️",
    color: "#25D366",
    useCases: ["devis-chantier", "suivi-travaux", "coordination-equipes"],
    stats: [
      { value: "+67%", label: { fr: "devis envoyés en 24h", en: "quotes sent within 24h", de: "Angebote innerhalb 24h" } },
      { value: "-40%", label: { fr: "temps coordination", en: "coordination time", de: "Koordinationszeit" } },
      { value: "4.7/5", label: { fr: "satisfaction clients", en: "client satisfaction", de: "Kundenzufriedenheit" } },
    ],
  },
  {
    slug: "education",
    icon: "🎓",
    color: "#25D366",
    useCases: ["inscription-formations", "suivi-apprenants", "support-pedagogique"],
    stats: [
      { value: "+52%", label: { fr: "inscriptions automatisées", en: "automated enrolments", de: "automatisierte Anmeldungen" } },
      { value: "-70%", label: { fr: "abandons de formation", en: "course dropouts", de: "Kursabbrüche" } },
      { value: "4.8/5", label: { fr: "satisfaction apprenants", en: "learner satisfaction", de: "Lernerzufriedenheit" } },
    ],
  },
  {
    slug: "automobile",
    icon: "🚗",
    color: "#25D366",
    useCases: ["prise-rdv-atelier", "relance-controle-technique", "devis-reparation"],
    stats: [
      { value: "+89%", label: { fr: "RDV atelier pris 24h/24", en: "workshop bookings 24/7", de: "Werkstatttermine 24/7" } },
      { value: "18%", label: { fr: "taux de relance CT", en: "MOT reminder conversion", de: "HU-Erinnerungsrate" } },
      { value: "-45%", label: { fr: "no-shows atelier", en: "workshop no-shows", de: "Werkstatt-No-Shows" } },
    ],
  },
  {
    slug: "juridique",
    icon: "⚖️",
    color: "#25D366",
    useCases: ["qualification-dossiers", "prise-rdv-consultation", "suivi-procedures"],
    stats: [
      { value: "80%", label: { fr: "dossiers pré-qualifiés", en: "pre-qualified files", de: "vorqualifizierte Akten" } },
      { value: "-60%", label: { fr: "temps secrétariat", en: "secretarial time", de: "Sekretariatszeit" } },
      { value: "+29%", label: { fr: "consultations facturées", en: "billed consultations", de: "abgerechnete Beratungen" } },
    ],
  },
  {
    slug: "beaute-bien-etre",
    icon: "💆",
    color: "#25D366",
    useCases: ["reservations-soins", "fidelisation-clients", "vente-produits"],
    stats: [
      { value: "+71%", label: { fr: "réservations en ligne", en: "online bookings", de: "Online-Buchungen" } },
      { value: "35%", label: { fr: "clients fidélisés", en: "returning customers", de: "Stammkunden" } },
      { value: "-0%", label: { fr: "commission Treatwell", en: "Treatwell commission", de: "Treatwell-Provision" } },
    ],
  },
  {
    slug: "logistique",
    icon: "📦",
    color: "#25D366",
    useCases: ["suivi-livraisons", "gestion-retours", "notifications-clients"],
    stats: [
      { value: "-73%", label: { fr: "appels WISMO entrants", en: "inbound WISMO calls", de: "eingehende WISMO-Anrufe" } },
      { value: "98%", label: { fr: "clients informés proactivement", en: "proactively informed", de: "proaktiv informiert" } },
      { value: "+22%", label: { fr: "NPS livraison", en: "delivery NPS", de: "Liefer-NPS" } },
    ],
  },
  {
    slug: "saas-tech",
    icon: "💻",
    color: "#25D366",
    useCases: ["onboarding-clients", "support-technique", "upsell-renouvellement"],
    stats: [
      { value: "-58%", label: { fr: "tickets support L1", en: "L1 support tickets", de: "L1-Support-Tickets" } },
      { value: "+34%", label: { fr: "taux d'activation", en: "activation rate", de: "Aktivierungsrate" } },
      { value: "4.6/5", label: { fr: "CSAT support", en: "support CSAT", de: "Support-CSAT" } },
    ],
  },
];

export const SECTEUR_TRANSLATIONS: Record<string, Record<string, SecteurTranslation>> = {
  immobilier: {
    fr: {
      name: "Immobilier",
      title: "Agent IA WhatsApp pour l'Immobilier",
      metaTitle: "Agent IA WhatsApp Immobilier — Qualifiez vos leads 24h/24",
      metaDescription: "Automatisez la qualification de leads immobiliers sur WhatsApp. Répondez aux prospects en 3 minutes, prenez des RDV automatiquement et relancez sans effort.",
      subtitle: "Qualifiez vos prospects immobiliers, prenez des rendez-vous et relancez automatiquement — sans décrocher votre téléphone.",
      useCases: ["Qualification automatique des leads portails (SeLoger, Leboncoin, PAP)", "Prise de RDV de visite directement dans votre agenda", "Relance des prospects non répondants à J+3, J+7, J+14", "Analyse des photos de bien envoyées par les clients", "Gestion des demandes de renseignements 24h/24"],
      painPoint: "Vous perdez des mandats parce que vous ne pouvez pas répondre à tous les prospects en moins de 5 minutes. En immobilier, le premier agent qui rappelle gagne le mandat.",
      solution: "Notre agent IA WhatsApp répond en 30 secondes, 7j/7, qualifie le projet (type de bien, budget, délai), et réserve la visite dans votre agenda — pendant que vous êtes en rendez-vous.",
      ctaText: "Voir une démo immobilier",
    },
    en: {
      name: "Real Estate",
      title: "WhatsApp AI Agent for Real Estate",
      metaTitle: "WhatsApp AI Agent Real Estate — Qualify your leads 24/7",
      metaDescription: "Automate real estate lead qualification on WhatsApp. Respond to prospects within 3 minutes, automatically book viewings and follow up effortlessly.",
      subtitle: "Qualify your real estate prospects, book appointments and follow up automatically — without picking up your phone.",
      useCases: ["Automatic lead qualification from portals (Rightmove, Zoopla, OnTheMarket)", "Direct viewing bookings into your calendar", "Automated follow-up at D+3, D+7, D+14", "Analysis of property photos sent by clients", "24/7 enquiry management"],
      painPoint: "You're losing listings because you can't respond to every prospect within 5 minutes. In real estate, the first agent to call back wins the instruction.",
      solution: "Our WhatsApp AI agent responds in 30 seconds, 7 days a week, qualifies the project (property type, budget, timeline), and books the viewing into your calendar — while you're in a meeting.",
      ctaText: "See a real estate demo",
    },
    de: {
      name: "Immobilien",
      title: "WhatsApp KI-Agent für Immobilien",
      metaTitle: "WhatsApp KI-Agent Immobilien — Qualifizieren Sie Leads 24/7",
      metaDescription: "Automatisieren Sie die Immobilien-Lead-Qualifizierung auf WhatsApp. Antworten Sie Interessenten in 3 Minuten, buchen Sie Besichtigungen automatisch.",
      subtitle: "Qualifizieren Sie Ihre Immobilieninteressenten, vereinbaren Sie Termine und folgen Sie automatisch nach — ohne Ihr Telefon abzuheben.",
      useCases: ["Automatische Lead-Qualifizierung von Portalen (Immoscout, Immowelt)", "Direktbuchung von Besichtigungsterminen in Ihren Kalender", "Automatisches Follow-up an T+3, T+7, T+14", "Analyse von Objektfotos, die von Kunden gesendet wurden", "24/7 Anfragenmanagement"],
      painPoint: "Sie verlieren Aufträge, weil Sie nicht in weniger als 5 Minuten auf jeden Interessenten antworten können. In der Immobilienbranche gewinnt der erste Makler, der zurückruft.",
      solution: "Unser WhatsApp KI-Agent antwortet in 30 Sekunden, 7 Tage die Woche, qualifiziert das Projekt und bucht die Besichtigung in Ihren Kalender — während Sie im Termin sind.",
      ctaText: "Immobilien-Demo ansehen",
    },
    nl: {
      name: "Vastgoed",
      title: "WhatsApp AI-agent voor Vastgoed",
      metaTitle: "WhatsApp AI-agent Vastgoed — Kwalificeer uw leads 24/7",
      metaDescription: "Automatiseer vastgoed leadkwalificatie op WhatsApp. Reageer op prospects binnen 3 minuten, boek bezichtigingen automatisch en volg op moeiteloos.",
      subtitle: "Kwalificeer uw vastgoedprospects, boek afspraken en volg automatisch op — zonder uw telefoon op te pakken.",
      useCases: ["Automatische leadkwalificatie van portalen (Funda, Pararius)", "Directe bezichtigingsboeking in uw agenda", "Geautomatiseerde opvolging op D+3, D+7, D+14", "Analyse van vastgoedfoto's verzonden door klanten", "24/7 verzoekenbeheer"],
      painPoint: "U verliest mandaten omdat u niet binnen 5 minuten op elke prospect kunt reageren. In vastgoed wint de eerste makelaar die terugbelt de opdracht.",
      solution: "Onze WhatsApp AI-agent reageert in 30 seconden, 7 dagen per week, kwalificeert het project en boekt de bezichtiging in uw agenda — terwijl u in een vergadering zit.",
      ctaText: "Bekijk een vastgoed demo",
    },
  },
  ecommerce: {
    fr: {
      name: "E-commerce",
      title: "Agent IA WhatsApp pour le E-commerce",
      metaTitle: "Agent IA WhatsApp E-commerce — Récupérez vos paniers abandonnés",
      metaDescription: "Automatisez le SAV e-commerce sur WhatsApp. Récupérez 26% de vos paniers abandonnés, réduisez les tickets support de 62% et fidélisez vos clients.",
      subtitle: "Récupérez vos paniers abandonnés, automatisez votre SAV et fidélisez vos clients e-commerce — sur le canal le plus lu au monde.",
      useCases: ["Relance automatique des paniers abandonnés (taux de récupération 26%)", "Suivi de commande en temps réel sans appel", "Gestion des retours et remboursements", "Recommandations produits personnalisées par IA", "Programme de fidélité et réactivation clients inactifs"],
      painPoint: "68% de vos visiteurs abandonnent leur panier. Vos emails de relance atteignent 18% d'ouverture. Votre service client croule sous les 'où est ma commande ?'.",
      solution: "L'agent IA récupère les abandons en 1h sur WhatsApp (98% d'ouverture), répond automatiquement aux questions de suivi, et segmente vos clients pour des campagnes de réactivation personnalisées.",
      ctaText: "Voir une démo e-commerce",
    },
    en: {
      name: "E-commerce",
      title: "WhatsApp AI Agent for E-commerce",
      metaTitle: "WhatsApp AI Agent E-commerce — Recover your abandoned carts",
      metaDescription: "Automate e-commerce customer service on WhatsApp. Recover 26% of abandoned carts, reduce support tickets by 62% and retain your customers.",
      subtitle: "Recover abandoned carts, automate customer service and retain your e-commerce customers — on the world's most-read channel.",
      useCases: ["Automatic abandoned cart recovery (26% recovery rate)", "Real-time order tracking without phone calls", "Returns and refund management", "AI-powered personalised product recommendations", "Loyalty programme and dormant customer reactivation"],
      painPoint: "68% of your visitors abandon their cart. Your follow-up emails achieve 18% open rates. Your customer service is drowning in 'where's my order?' enquiries.",
      solution: "The AI agent recovers abandonments within 1 hour on WhatsApp (98% open rate), automatically handles tracking queries, and segments your customers for personalised reactivation campaigns.",
      ctaText: "See an e-commerce demo",
    },
    de: {
      name: "E-Commerce",
      title: "WhatsApp KI-Agent für E-Commerce",
      metaTitle: "WhatsApp KI-Agent E-Commerce — Warenkörbe zurückgewinnen",
      metaDescription: "Automatisieren Sie den E-Commerce-Kundenservice auf WhatsApp. Gewinnen Sie 26% der abgebrochenen Warenkörbe zurück, reduzieren Sie Support-Tickets um 62%.",
      subtitle: "Gewinnen Sie abgebrochene Warenkörbe zurück, automatisieren Sie Ihren Kundenservice und binden Sie Ihre E-Commerce-Kunden — auf dem meistgelesenen Kanal der Welt.",
      useCases: ["Automatische Warenkorb-Wiederherstellung (26% Rückgewinnungsrate)", "Echtzeit-Bestellverfolgung ohne Anrufe", "Rücksendungs- und Erstattungsmanagement", "KI-gestützte personalisierte Produktempfehlungen", "Treueprogramm und Reaktivierung inaktiver Kunden"],
      painPoint: "68% Ihrer Besucher brechen den Warenkorb ab. Ihre Folge-E-Mails erreichen 18% Öffnungsraten. Ihr Kundendienst ertrinkt in 'Wo ist meine Bestellung?'-Anfragen.",
      solution: "Der KI-Agent gewinnt Abbrüche innerhalb von 1 Stunde auf WhatsApp zurück (98% Öffnungsrate), beantwortet automatisch Tracking-Fragen und segmentiert Ihre Kunden für personalisierte Reaktivierungskampagnen.",
      ctaText: "E-Commerce-Demo ansehen",
    },
    nl: {
      name: "E-commerce",
      title: "WhatsApp AI-agent voor E-commerce",
      metaTitle: "WhatsApp AI-agent E-commerce — Herstel uw verlaten winkelwagens",
      metaDescription: "Automatiseer e-commerce klantenservice op WhatsApp. Herstel 26% van verlaten winkelwagens, reduceer supporttickets met 62% en behoud uw klanten.",
      subtitle: "Herstel verlaten winkelwagens, automatiseer klantenservice en behoud uw e-commerce klanten — op het meest gelezen kanaal ter wereld.",
      useCases: ["Automatisch herstel van verlaten winkelwagens (26% herstelpercentage)", "Realtime bestellingstracking zonder telefoontjes", "Retour- en terugbetalingsbeheer", "AI-gestuurde gepersonaliseerde productaanbevelingen", "Loyaliteitsprogramma en reactivering van slapende klanten"],
      painPoint: "68% van uw bezoekers verlaat hun winkelwagen. Uw follow-up e-mails bereiken 18% openingspercentages. Uw klantenservice verdrinkt in 'waar is mijn bestelling?'-vragen.",
      solution: "De AI-agent herstelt verlaten wagens binnen 1 uur op WhatsApp (98% openingspercentage), beantwoordt automatisch tracking vragen en segmenteert uw klanten voor gepersonaliseerde reactiveringscampagnes.",
      ctaText: "Bekijk een e-commerce demo",
    },
  },
  sante: {
    fr: {
      name: "Santé",
      title: "Agent IA WhatsApp pour la Santé",
      metaTitle: "Agent IA WhatsApp Santé — Agenda automatisé et rappels patients",
      metaDescription: "Automatisez la prise de rendez-vous médicaux sur WhatsApp. Réduisez les no-shows de 61%, gérez votre agenda 24h/24 et envoyez des rappels personnalisés.",
      subtitle: "Gérez votre agenda médical 24h/24, réduisez les no-shows et améliorez l'expérience patient — en toute conformité RGPD.",
      useCases: ["Prise de RDV médicaux 24h/24 sans secrétaire", "Rappels automatiques J-48h et J-24h avec confirmation", "Pré-anamnèse et collecte d'informations patients", "Gestion des annulations et créneaux libérés", "Ordonnances et résultats envoyés sécurisés via WhatsApp"],
      painPoint: "23% de no-shows. Secrétaire saturée. Patients qui ne trouvent pas de créneau en ligne et appellent. L'agenda n'est jamais optimisé.",
      solution: "L'agent répond aux demandes de RDV à 2h du matin, envoie des rappels automatiques, et propose les créneaux libérés en temps réel — avec confirmation immédiate par le patient.",
      ctaText: "Voir une démo santé",
    },
    en: {
      name: "Healthcare",
      title: "WhatsApp AI Agent for Healthcare",
      metaTitle: "WhatsApp AI Agent Healthcare — Automated scheduling and patient reminders",
      metaDescription: "Automate medical appointment booking on WhatsApp. Reduce no-shows by 61%, manage your schedule 24/7 and send personalised reminders.",
      subtitle: "Manage your medical schedule 24/7, reduce no-shows and improve patient experience — fully GDPR compliant.",
      useCases: ["24/7 medical appointment booking without a receptionist", "Automatic reminders 48h and 24h before with confirmation", "Pre-consultation and patient information collection", "Cancellation management and released slot notifications", "Secure prescriptions and results sent via WhatsApp"],
      painPoint: "23% no-shows. Overwhelmed receptionist. Patients unable to find an online slot calling in. The schedule is never optimised.",
      solution: "The agent handles appointment requests at 2am, sends automatic reminders, and offers released slots in real-time — with immediate patient confirmation.",
      ctaText: "See a healthcare demo",
    },
    de: {
      name: "Gesundheit",
      title: "WhatsApp KI-Agent für Gesundheitswesen",
      metaTitle: "WhatsApp KI-Agent Gesundheit — Automatisierte Terminverwaltung",
      metaDescription: "Automatisieren Sie medizinische Terminbuchungen auf WhatsApp. Reduzieren Sie No-Shows um 61%, verwalten Sie Ihren Kalender 24/7.",
      subtitle: "Verwalten Sie Ihren medizinischen Kalender 24/7, reduzieren Sie No-Shows und verbessern Sie das Patientenerlebnis — vollständig DSGVO-konform.",
      useCases: ["24/7-Terminbuchung ohne Empfangspersonal", "Automatische Erinnerungen 48h und 24h vorher mit Bestätigung", "Voranamnese und Patientendatenerfassung", "Stornierungsmanagement und freigewordene Slots", "Sichere Rezepte und Ergebnisse über WhatsApp"],
      painPoint: "23% No-Shows. Überlastetes Empfangspersonal. Patienten, die keinen Online-Termin finden und anrufen. Der Kalender ist nie optimiert.",
      solution: "Der Agent bearbeitet Terminanfragen um 2 Uhr morgens, sendet automatische Erinnerungen und bietet freigewordene Slots in Echtzeit an.",
      ctaText: "Gesundheits-Demo ansehen",
    },
    nl: {
      name: "Gezondheidszorg",
      title: "WhatsApp AI-agent voor de Gezondheidszorg",
      metaTitle: "WhatsApp AI-agent Gezondheidszorg — Geautomatiseerde planning en patiëntherinneringen",
      metaDescription: "Automatiseer medische afsprakenboeking op WhatsApp. Reduceer no-shows met 61%, beheer uw agenda 24/7 en stuur gepersonaliseerde herinneringen.",
      subtitle: "Beheer uw medische agenda 24/7, reduceer no-shows en verbeter de patiëntervaring — volledig AVG-conform.",
      useCases: ["24/7 medische afsprakenboeking zonder receptionist", "Automatische herinneringen 48u en 24u van tevoren met bevestiging", "Pre-consultatie en patiëntgegevensverzameling", "Annuleringsbeheer en vrijgekomen tijdslotmeldingen", "Veilige recepten en resultaten verzonden via WhatsApp"],
      painPoint: "23% no-shows. Overweldigde receptionist. Patiënten die geen online tijdslot vinden en bellen. De agenda is nooit geoptimaliseerd.",
      solution: "De agent verwerkt afspraakverzoeken om 2 uur 's nachts, stuurt automatische herinneringen en biedt vrijgekomen tijdslots in realtime aan.",
      ctaText: "Bekijk een gezondheidszorg demo",
    },
  },
  restaurant: {
    fr: {
      name: "Restauration",
      title: "Agent IA WhatsApp pour la Restauration",
      metaTitle: "Agent IA WhatsApp Restaurant — Réservations et commandes automatisées",
      metaDescription: "Automatisez les réservations et commandes click & collect de votre restaurant sur WhatsApp. Zéro commission, clients fidélisés, salle toujours optimisée.",
      subtitle: "Gérez vos réservations, commandes click & collect et fidélisation client sans payer de commission à des plateformes tierces.",
      useCases: ["Réservations de table automatiques avec confirmation instantanée", "Commandes click & collect et livraison sans commission", "Relance automatique des clients inactifs avec offre personnalisée", "Gestion des menus, allergènes et plats du jour en temps réel", "Programme de fidélité et collecte d'avis Google"],
      painPoint: "TheFork prend 2€ par couvert. Uber Eats 30% de commission. Vous n'avez aucun accès aux données de vos clients — et aucun moyen de les fidéliser directement.",
      solution: "L'agent WhatsApp prend les réservations et commandes directement, sans intermédiaire. Vos clients vous appartiennent. Vous les relancez, vous les fidélisez, vous collectez les avis.",
      ctaText: "Voir une démo restaurant",
    },
    en: {
      name: "Restaurant",
      title: "WhatsApp AI Agent for Restaurants",
      metaTitle: "WhatsApp AI Agent Restaurant — Automated reservations and orders",
      metaDescription: "Automate your restaurant reservations and click & collect orders on WhatsApp. Zero commission, loyal customers, always-optimised dining room.",
      subtitle: "Manage your reservations, click & collect orders and customer loyalty without paying commissions to third-party platforms.",
      useCases: ["Automatic table reservations with instant confirmation", "Click & collect and delivery orders without commission", "Automatic re-engagement of inactive customers with personalised offer", "Real-time menu, allergen and daily specials management", "Loyalty programme and Google review collection"],
      painPoint: "OpenTable charges per cover. Deliveroo takes 30% commission. You have no access to your customers' data — and no way to build direct loyalty.",
      solution: "The WhatsApp agent takes reservations and orders directly, no middleman. Your customers belong to you. You re-engage them, build loyalty, collect reviews.",
      ctaText: "See a restaurant demo",
    },
    de: {
      name: "Gastronomie",
      title: "WhatsApp KI-Agent für Gastronomie",
      metaTitle: "WhatsApp KI-Agent Restaurant — Automatisierte Reservierungen und Bestellungen",
      metaDescription: "Automatisieren Sie Restaurantreservierungen und Click & Collect-Bestellungen auf WhatsApp. Null Provision, treue Kunden, immer optimierter Speisesaal.",
      subtitle: "Verwalten Sie Reservierungen, Click & Collect-Bestellungen und Kundenbindung — ohne Provision an Drittplattformen zu zahlen.",
      useCases: ["Automatische Tischreservierungen mit sofortiger Bestätigung", "Click & Collect und Lieferbestellungen ohne Provision", "Automatische Reaktivierung inaktiver Kunden", "Echtzeit-Menü-, Allergen- und Tagesgerichtverwaltung", "Treueprogramm und Google-Bewertungssammlung"],
      painPoint: "OpenTable berechnet pro Gast. Lieferando nimmt 30% Provision. Sie haben keinen Zugang zu Kundendaten — und keine Möglichkeit, direkt Kundentreue aufzubauen.",
      solution: "Der WhatsApp-Agent nimmt Reservierungen und Bestellungen direkt an, ohne Mittelsmänner. Ihre Kunden gehören Ihnen.",
      ctaText: "Gastronomie-Demo ansehen",
    },
    nl: {
      name: "Horeca",
      title: "WhatsApp AI-agent voor Horeca",
      metaTitle: "WhatsApp AI-agent Restaurant — Geautomatiseerde reserveringen en bestellingen",
      metaDescription: "Automatiseer restaurantreserveringen en click & collect bestellingen op WhatsApp. Nul commissie, loyale klanten, altijd geoptimaliseerde bezetting.",
      subtitle: "Beheer uw reserveringen, click & collect bestellingen en klantloyaliteit zonder commissie te betalen aan externe platforms.",
      useCases: ["Automatische tafelreserveringen met directe bevestiging", "Click & collect en bezorgbestellingen zonder commissie", "Automatische heractivering van inactieve klanten", "Realtime menu-, allergeen- en dagspecialiteiteningbeheer", "Loyaliteitsprogramma en Google-recensieverzameling"],
      painPoint: "Iens rekent per couverts. Thuisbezorgd neemt 30% commissie. U heeft geen toegang tot uw klantgegevens — en geen manier om directe loyaliteit op te bouwen.",
      solution: "De WhatsApp-agent neemt reserveringen en bestellingen direct aan, zonder tussenpersoon. Uw klanten zijn van u. U heractiveer hen, bouwt loyaliteit op en verzamelt recensies.",
      ctaText: "Bekijk een horeca demo",
    },
  },
  assurance: {
    fr: {
      name: "Assurance",
      title: "Agent IA WhatsApp pour l'Assurance",
      metaTitle: "Agent IA WhatsApp Assurance — Devis automatiques et gestion sinistres",
      metaDescription: "Automatisez les devis d'assurance et la gestion des sinistres sur WhatsApp. Générez un devis en 5 minutes, traitez les déclarations 24h/24.",
      subtitle: "Générez des devis en 5 minutes, gérez les sinistres et relancez les renouvellements — sans surcharger vos conseillers.",
      useCases: ["Génération automatique de devis (auto, habitation, santé, prévoyance)", "Déclaration et suivi de sinistres via WhatsApp", "Relance automatique des renouvellements à J-60, J-30, J-7", "Collecte de pièces justificatives (photos, documents)", "Qualification et routage des demandes complexes"],
      painPoint: "Vos conseillers passent 60% de leur temps sur des tâches répétitives : devis simples, suivi de dossiers, collecte de pièces. Pendant ce temps, les leads complexes attendent.",
      solution: "L'agent gère les devis et sinistres simples en autonomie. Vos conseillers se concentrent sur les dossiers à valeur. Résultat : +38% de taux de conversion, -55% de coût de traitement.",
      ctaText: "Voir une démo assurance",
    },
    en: {
      name: "Insurance",
      title: "WhatsApp AI Agent for Insurance",
      metaTitle: "WhatsApp AI Agent Insurance — Automated quotes and claims management",
      metaDescription: "Automate insurance quotes and claims management on WhatsApp. Generate a quote in 5 minutes, process declarations 24/7.",
      subtitle: "Generate quotes in 5 minutes, manage claims and follow up renewals — without overloading your advisors.",
      useCases: ["Automatic quote generation (motor, home, health, life)", "Claims declaration and tracking via WhatsApp", "Automated renewal reminders at D-60, D-30, D-7", "Supporting document collection (photos, documents)", "Complex request qualification and routing"],
      painPoint: "Your advisors spend 60% of their time on repetitive tasks: simple quotes, file tracking, document collection. Meanwhile, complex leads are waiting.",
      solution: "The agent handles simple quotes and claims autonomously. Your advisors focus on high-value files. Result: +38% conversion rate, -55% processing cost.",
      ctaText: "See an insurance demo",
    },
    de: {
      name: "Versicherung",
      title: "WhatsApp KI-Agent für Versicherungen",
      metaTitle: "WhatsApp KI-Agent Versicherung — Automatisierte Angebote und Schadenmanagement",
      metaDescription: "Automatisieren Sie Versicherungsangebote und Schadenmanagement auf WhatsApp. Erstellen Sie ein Angebot in 5 Minuten, bearbeiten Sie Meldungen 24/7.",
      subtitle: "Erstellen Sie Angebote in 5 Minuten, verwalten Sie Schäden und folgen Sie Verlängerungen nach — ohne Ihre Berater zu überlasten.",
      useCases: ["Automatische Angebotserstellung (Auto, Haus, Gesundheit, Vorsorge)", "Schadensmeldung und -verfolgung über WhatsApp", "Automatische Verlängerungserinnerungen T-60, T-30, T-7", "Dokumentensammlung (Fotos, Unterlagen)", "Qualifizierung und Weiterleitung komplexer Anfragen"],
      painPoint: "Ihre Berater verbringen 60% ihrer Zeit mit repetitiven Aufgaben: einfache Angebote, Aktenbearbeitung, Dokumentensammlung.",
      solution: "Der Agent bearbeitet einfache Angebote und Schäden selbstständig. Ihre Berater konzentrieren sich auf wertvolle Akten. Ergebnis: +38% Konversionsrate, -55% Bearbeitungskosten.",
      ctaText: "Versicherungs-Demo ansehen",
    },
    nl: {
      name: "Verzekeringen",
      title: "WhatsApp AI-agent voor Verzekeringen",
      metaTitle: "WhatsApp AI-agent Verzekeringen — Geautomatiseerde offertes en schadebeheer",
      metaDescription: "Automatiseer verzekeringsoffertes en schadebeheer op WhatsApp. Genereer een offerte in 5 minuten, verwerk meldingen 24/7.",
      subtitle: "Genereer offertes in 5 minuten, beheer schademeldingen en volg verlengingen op — zonder uw adviseurs te overbelasten.",
      useCases: ["Automatische offertegeneratie (auto, woning, gezondheid, leven)", "Schadeclaiming en -opvolging via WhatsApp", "Automatische verlengingsherinneringen op D-60, D-30, D-7", "Verzameling van bewijsdocumenten (foto's, documenten)", "Kwalificatie en routering van complexe verzoeken"],
      painPoint: "Uw adviseurs besteden 60% van hun tijd aan repetitieve taken: eenvoudige offertes, dossieropvolging, documentenverzameling. Ondertussen wachten complexe leads.",
      solution: "De agent verwerkt eenvoudige offertes en schades zelfstandig. Uw adviseurs richten zich op waardevolle dossiers. Resultaat: +38% conversiepercentage, -55% verwerkingskosten.",
      ctaText: "Bekijk een verzekeringen demo",
    },
  },
  btp: {
    fr: {
      name: "BTP",
      title: "Agent IA WhatsApp pour le BTP",
      metaTitle: "Agent IA WhatsApp BTP — Devis chantier et coordination automatisés",
      metaDescription: "Automatisez les devis BTP et la coordination de chantier sur WhatsApp. Envoyez 67% de devis supplémentaires en 24h, réduisez le temps de coordination de 40%.",
      subtitle: "Envoyez vos devis plus vite, coordonnez vos équipes efficacement et ne ratez plus aucune opportunité — même en plein chantier.",
      useCases: ["Génération de devis rapide à partir de photos de chantier", "Coordination des équipes et sous-traitants via WhatsApp", "Suivi avancement travaux avec photos quotidiennes", "Relance automatique des devis non acceptés", "Gestion des approvisionnements et commandes fournisseurs"],
      painPoint: "Vous ratez des chantiers parce que votre devis met 5 jours. Vos équipes perdent 2h/jour en coordination téléphonique. Les clients appellent pour savoir où en sont les travaux.",
      solution: "L'agent collecte les infos par WhatsApp, génère un devis en 2h, coordonne les équipes par message, et envoie des rapports d'avancement quotidiens aux clients.",
      ctaText: "Voir une démo BTP",
    },
    en: {
      name: "Construction",
      title: "WhatsApp AI Agent for Construction",
      metaTitle: "WhatsApp AI Agent Construction — Automated quotes and site coordination",
      metaDescription: "Automate construction quotes and site coordination on WhatsApp. Send 67% more quotes within 24h, reduce coordination time by 40%.",
      subtitle: "Send quotes faster, coordinate your teams efficiently and never miss an opportunity — even on site.",
      useCases: ["Quick quote generation from site photos", "Team and subcontractor coordination via WhatsApp", "Daily progress tracking with photos", "Automatic follow-up on pending quotes", "Supply and purchase order management"],
      painPoint: "You're losing contracts because your quote takes 5 days. Your teams waste 2 hours a day on phone coordination. Clients call to check on progress.",
      solution: "The agent collects information via WhatsApp, generates a quote in 2 hours, coordinates teams by message, and sends daily progress reports to clients.",
      ctaText: "See a construction demo",
    },
    de: {
      name: "Bauwesen",
      title: "WhatsApp KI-Agent für das Bauwesen",
      metaTitle: "WhatsApp KI-Agent Bauwesen — Automatisierte Angebote und Baustellenkoordination",
      metaDescription: "Automatisieren Sie Bauangebote und Baustellenkoordination auf WhatsApp. Senden Sie 67% mehr Angebote innerhalb von 24h.",
      subtitle: "Senden Sie Angebote schneller, koordinieren Sie Ihre Teams effizient und verpassen Sie keine Gelegenheit mehr — auch auf der Baustelle.",
      useCases: ["Schnelle Angebotserstellung aus Baustellenfotos", "Team- und Subunternehmerkoordination über WhatsApp", "Tägliche Fortschrittsverfolgung mit Fotos", "Automatisches Follow-up ausstehender Angebote", "Liefer- und Bestellmanagement"],
      painPoint: "Sie verlieren Aufträge, weil Ihr Angebot 5 Tage dauert. Ihre Teams verschwenden 2 Stunden täglich mit telefonischer Koordination.",
      solution: "Der Agent sammelt Informationen über WhatsApp, erstellt ein Angebot in 2 Stunden und sendet tägliche Fortschrittsberichte an Kunden.",
      ctaText: "Bauwesen-Demo ansehen",
    },
    nl: {
      name: "Bouw & Installatie",
      title: "WhatsApp AI-agent voor de Bouw",
      metaTitle: "WhatsApp AI-agent Bouw — Geautomatiseerde offertes en projectcoördinatie",
      metaDescription: "Automatiseer bouwoffertes en projectcoördinatie op WhatsApp. Stuur 67% meer offertes binnen 24u, reduceer coördinatietijd met 40%.",
      subtitle: "Stuur offertes sneller, coördineer uw teams efficiënt en mis geen enkele kans meer — ook op de bouwplaats.",
      useCases: ["Snelle offertegeneratie vanuit bouwplaatsfoto's", "Team- en onderaannemercoördinatie via WhatsApp", "Dagelijkse voortgangsregistratie met foto's", "Automatische opvolging van openstaande offertes", "Bevoorradingsbeheer"],
      painPoint: "U verliest opdrachten omdat uw offerte 5 dagen duurt. Uw teams verspillen 2 uur per dag aan telefonische coördinatie. Klanten bellen om te vragen hoe het staat.",
      solution: "De agent verzamelt informatie via WhatsApp, genereert een offerte in 2 uur, coördineert teams via berichten en stuurt dagelijkse voortgangsrapporten naar klanten.",
      ctaText: "Bekijk een bouw demo",
    },
  },
  education: {
    fr: {
      name: "Éducation & Formation",
      title: "Agent IA WhatsApp pour l'Éducation et la Formation",
      metaTitle: "Agent IA WhatsApp Formation — Inscriptions automatisées et suivi apprenants",
      metaDescription: "Automatisez les inscriptions de formation et le suivi des apprenants sur WhatsApp. +52% d'inscriptions, -70% d'abandons, satisfaction 4.8/5.",
      subtitle: "Automatisez vos inscriptions, accompagnez vos apprenants et réduisez les abandons — pour des formations qui livrent leurs promesses.",
      useCases: ["Inscriptions et pré-inscriptions automatisées 24h/24", "Relance des prospects ayant consulté le catalogue", "Suivi hebdomadaire des apprenants et alertes décrochage", "Support pédagogique de premier niveau par IA", "Collecte de témoignages et avis certifiés"],
      painPoint: "30% des inscrits abandonnent avant la fin. Votre équipe pédagogique est débordée. Les prospects intéressés ne passent pas à l'acte parce que personne ne les relance.",
      solution: "L'agent inscrit les candidats, les accompagne tout au long de la formation avec des check-ins hebdomadaires, et détecte les signaux d'abandon pour déclencher une intervention humaine.",
      ctaText: "Voir une démo formation",
    },
    en: {
      name: "Education & Training",
      title: "WhatsApp AI Agent for Education and Training",
      metaTitle: "WhatsApp AI Agent Training — Automated enrolments and learner tracking",
      metaDescription: "Automate training enrolments and learner tracking on WhatsApp. +52% enrolments, -70% dropouts, 4.8/5 satisfaction.",
      subtitle: "Automate your enrolments, support your learners and reduce dropouts — for training programmes that deliver on their promises.",
      useCases: ["24/7 automated enrolments and pre-enrolments", "Re-engagement of prospects who browsed the catalogue", "Weekly learner check-ins and dropout alerts", "First-level pedagogical support by AI", "Testimonial and certified review collection"],
      painPoint: "30% of enrolled learners drop out before completion. Your teaching team is overwhelmed. Interested prospects don't convert because no one follows up.",
      solution: "The agent enrols candidates, supports them throughout the training with weekly check-ins, and detects dropout signals to trigger human intervention.",
      ctaText: "See a training demo",
    },
    de: {
      name: "Bildung & Weiterbildung",
      title: "WhatsApp KI-Agent für Bildung und Weiterbildung",
      metaTitle: "WhatsApp KI-Agent Weiterbildung — Automatisierte Anmeldungen und Lernerverfolgung",
      metaDescription: "Automatisieren Sie Kursanmeldungen und Lernerverfolgung auf WhatsApp. +52% Anmeldungen, -70% Abbrüche, 4,8/5 Zufriedenheit.",
      subtitle: "Automatisieren Sie Anmeldungen, unterstützen Sie Ihre Lernenden und reduzieren Sie Abbrüche.",
      useCases: ["24/7-Kursanmeldungen und Voranmeldungen", "Reaktivierung von Interessenten, die den Katalog durchsucht haben", "Wöchentliche Lerner-Check-ins und Abbruchsalarme", "Pädagogischer Erstlevel-Support durch KI", "Sammlung von Erfahrungsberichten und zertifizierten Bewertungen"],
      painPoint: "30% der eingeschriebenen Lernenden brechen vor Abschluss ab. Ihr Lehrteam ist überlastet. Interessierte Interessenten konvertieren nicht, weil niemand nachfasst.",
      solution: "Der Agent meldet Kandidaten an, begleitet sie durch wöchentliche Check-ins und erkennt Abbruchsignale für menschliche Intervention.",
      ctaText: "Weiterbildungs-Demo ansehen",
    },
    nl: {
      name: "Opleiding & Onderwijs",
      title: "WhatsApp AI-agent voor Opleiding en Onderwijs",
      metaTitle: "WhatsApp AI-agent Opleiding — Geautomatiseerde inschrijvingen en leerlingopvolging",
      metaDescription: "Automatiseer opleidingsinschrijvingen en leerlingopvolging op WhatsApp. +52% inschrijvingen, -70% uitval, 4,8/5 tevredenheid.",
      subtitle: "Automatiseer uw inschrijvingen, begeleid uw leerlingen en reduceer uitval — voor opleidingen die hun beloften waarmaken.",
      useCases: ["24/7 geautomatiseerde inschrijvingen en pre-inschrijvingen", "Heractivering van prospects die de catalogus hebben bekeken", "Wekelijkse check-ins met leerlingen en uitvalmeldingen", "Eerste niveau pedagogische ondersteuning door AI", "Verzameling van getuigenissen en gecertificeerde recensies"],
      painPoint: "30% van de ingeschreven leerlingen valt uit voor het einde. Uw onderwijsteam is overweldigd. Geïnteresseerde prospects converteren niet omdat niemand opvolgt.",
      solution: "De agent schrijft kandidaten in, begeleidt hen door wekelijkse check-ins en detecteert uitvalsignalen voor menselijke interventie.",
      ctaText: "Bekijk een opleiding demo",
    },
  },
  automobile: {
    fr: {
      name: "Automobile",
      title: "Agent IA WhatsApp pour l'Automobile",
      metaTitle: "Agent IA WhatsApp Automobile — RDV atelier et relance contrôle technique",
      metaDescription: "Automatisez les RDV d'atelier et les relances contrôle technique sur WhatsApp. +89% de RDV pris 24h/24, -45% de no-shows atelier.",
      subtitle: "Remplissez votre planning atelier automatiquement, relancez les CT et fidélisez vos clients sans effort supplémentaire.",
      useCases: ["Prise de RDV atelier 24h/24 avec rappels automatiques", "Relance contrôle technique 2 mois avant échéance", "Devis réparation sur photo des dégâts", "Suivi véhicule et notifications client en temps réel", "Campagnes de renouvellement et ventes additionnelles"],
      painPoint: "Votre planning atelier n'est jamais plein. Les clients oublient leur CT. Vos techniciens perdent du temps à appeler pour confirmer les RDV.",
      solution: "L'agent remplit votre agenda en automatique, relance chaque client 2 mois avant son CT, et envoie un rappel 48h avant son RDV — avec confirmation en un clic.",
      ctaText: "Voir une démo automobile",
    },
    en: {
      name: "Automotive",
      title: "WhatsApp AI Agent for Automotive",
      metaTitle: "WhatsApp AI Agent Automotive — Workshop bookings and MOT reminders",
      metaDescription: "Automate workshop bookings and MOT reminders on WhatsApp. +89% bookings 24/7, -45% workshop no-shows.",
      subtitle: "Fill your workshop schedule automatically, follow up MOTs and retain customers without extra effort.",
      useCases: ["24/7 workshop bookings with automatic reminders", "MOT reminders 2 months before expiry", "Repair quotes from damage photos", "Real-time vehicle tracking and customer notifications", "Renewal campaigns and upselling"],
      painPoint: "Your workshop schedule is never full. Customers forget their MOT. Your technicians waste time calling to confirm bookings.",
      solution: "The agent fills your schedule automatically, follows up each customer 2 months before their MOT, and sends a reminder 48h before their appointment — with one-click confirmation.",
      ctaText: "See an automotive demo",
    },
    de: {
      name: "Automobilbranche",
      title: "WhatsApp KI-Agent für die Automobilbranche",
      metaTitle: "WhatsApp KI-Agent Automobil — Werkstatttermine und HU-Erinnerungen",
      metaDescription: "Automatisieren Sie Werkstatttermine und HU-Erinnerungen auf WhatsApp. +89% Buchungen 24/7, -45% Werkstatt-No-Shows.",
      subtitle: "Füllen Sie Ihren Werkstattplan automatisch, verfolgen Sie Hauptuntersuchungen und binden Sie Kunden ohne Mehraufwand.",
      useCases: ["24/7-Werkstattbuchungen mit automatischen Erinnerungen", "HU-Erinnerungen 2 Monate vor Ablauf", "Reparaturangebote aus Schadensfotos", "Echtzeit-Fahrzeugverfolgung und Kundenbenachrichtigungen", "Erneuerungskampagnen und Upselling"],
      painPoint: "Ihr Werkstattplan ist nie voll. Kunden vergessen ihre HU. Ihre Techniker verschwenden Zeit mit Bestätigungsanrufen.",
      solution: "Der Agent füllt Ihren Kalender automatisch, erinnert jeden Kunden 2 Monate vor seiner HU und sendet 48h vor dem Termin eine Erinnerung.",
      ctaText: "Automobil-Demo ansehen",
    },
    nl: {
      name: "Automotive",
      title: "WhatsApp AI-agent voor de Automotive",
      metaTitle: "WhatsApp AI-agent Automotive — Werkplaatsafspraken en APK-herinneringen",
      metaDescription: "Automatiseer werkplaatsafspraken en APK-herinneringen op WhatsApp. +89% boekingen 24/7, -45% werkplaats no-shows.",
      subtitle: "Vul uw werkplaatsplanning automatisch, volg APK's op en behoud klanten zonder extra inspanning.",
      useCases: ["24/7 werkplaatsboekingen met automatische herinneringen", "APK-herinneringen 2 maanden voor vervaldatum", "Reparatieoffertes op basis van schaderfoto's", "Realtime voertuigtracking en klantmeldingen", "Verlengingscampagnes en upselling"],
      painPoint: "Uw werkplaatsplanning is nooit vol. Klanten vergeten hun APK. Uw technici verspillen tijd met bevestigingsoproepen.",
      solution: "De agent vult uw agenda automatisch, herinnert elke klant 2 maanden voor zijn APK en stuurt 48u voor de afspraak een herinnering met één-klik bevestiging.",
      ctaText: "Bekijk een automotive demo",
    },
  },
  juridique: {
    fr: {
      name: "Juridique",
      title: "Agent IA WhatsApp pour les Cabinets Juridiques",
      metaTitle: "Agent IA WhatsApp Juridique — Qualification dossiers et prise de RDV",
      metaDescription: "Automatisez la qualification des dossiers juridiques sur WhatsApp. 80% de dossiers pré-qualifiés, -60% de temps secrétariat, +29% de consultations facturées.",
      subtitle: "Pré-qualifiez les dossiers, remplissez votre agenda de consultations et réduisez la charge de secrétariat — sans compromis sur la confidentialité.",
      useCases: ["Pré-qualification automatique des demandes de consultation", "Collecte sécurisée des documents (pièces d'identité, contrats)", "Prise de RDV de consultation en ligne 24h/24", "Suivi des dossiers en cours et relances clients", "Collecte d'avis et témoignages post-consultation"],
      painPoint: "Votre secrétaire filtre les appels toute la journée. 40% des demandes ne sont pas dans votre domaine d'expertise. Vos consultations ne sont pas assez remplies.",
      solution: "L'agent pré-qualifie chaque demande (type de litige, urgence, budget), collecte les documents nécessaires et remplit votre agenda avec des consultations pertinentes.",
      ctaText: "Voir une démo juridique",
    },
    en: {
      name: "Legal",
      title: "WhatsApp AI Agent for Law Firms",
      metaTitle: "WhatsApp AI Agent Legal — Case qualification and consultation booking",
      metaDescription: "Automate legal case qualification on WhatsApp. 80% pre-qualified cases, -60% secretarial time, +29% billed consultations.",
      subtitle: "Pre-qualify cases, fill your consultation schedule and reduce secretarial workload — without compromising confidentiality.",
      useCases: ["Automatic pre-qualification of consultation requests", "Secure document collection (ID, contracts)", "Online 24/7 consultation booking", "Ongoing case tracking and client follow-up", "Post-consultation review and testimonial collection"],
      painPoint: "Your receptionist filters calls all day. 40% of enquiries are outside your area of expertise. Your consultation slots aren't full enough.",
      solution: "The agent pre-qualifies each enquiry (dispute type, urgency, budget), collects necessary documents and fills your schedule with relevant consultations.",
      ctaText: "See a legal demo",
    },
    de: {
      name: "Rechtswesen",
      title: "WhatsApp KI-Agent für Anwaltskanzleien",
      metaTitle: "WhatsApp KI-Agent Recht — Aktenqualifizierung und Terminbuchung",
      metaDescription: "Automatisieren Sie die Qualifizierung von Rechtsangelegenheiten auf WhatsApp. 80% vorqualifizierte Akten, -60% Sekretariatszeit.",
      subtitle: "Qualifizieren Sie Akten vor, füllen Sie Ihren Beratungskalender und reduzieren Sie den Sekretariatsaufwand — ohne Kompromisse bei der Vertraulichkeit.",
      useCases: ["Automatische Vorabqualifizierung von Beratungsanfragen", "Sichere Dokumentensammlung (Ausweise, Verträge)", "Online-24/7-Beratungsbuchungen", "Laufende Aktenverfolgung und Kunden-Follow-up", "Bewertungssammlung nach Beratungen"],
      painPoint: "Ihre Sekretärin filtert den ganzen Tag Anrufe. 40% der Anfragen liegen außerhalb Ihres Fachgebiets. Ihre Beratungsslots sind nicht gut genug gefüllt.",
      solution: "Der Agent qualifiziert jede Anfrage vor, sammelt notwendige Dokumente und füllt Ihren Kalender mit relevanten Beratungen.",
      ctaText: "Rechts-Demo ansehen",
    },
    nl: {
      name: "Juridisch",
      title: "WhatsApp AI-agent voor Juridische Kantoren",
      metaTitle: "WhatsApp AI-agent Juridisch — Dossierkwalificatie en consultatieboeking",
      metaDescription: "Automatiseer juridische dossierkwalificatie op WhatsApp. 80% vooraf gekwalificeerde dossiers, -60% secretariaatstijd, +29% gefactureerde consultaties.",
      subtitle: "Kwalificeer dossiers vooraf, vul uw consultatieagenda en reduceer de secretariaatswerkdruk — zonder inbreuk op vertrouwelijkheid.",
      useCases: ["Automatische vooraf kwalificatie van consultatieaanvragen", "Veilige documentenverzameling (ID, contracten)", "Online 24/7 consultatieboeking", "Lopende dossiersopvolging en klantopvolging", "Recensieverzameling na consultaties"],
      painPoint: "Uw secretaresse filtert de hele dag telefoongesprekken. 40% van de aanvragen valt buiten uw expertisegebied. Uw consultatietijdslots zijn niet goed genoeg gevuld.",
      solution: "De agent kwalificeert elk verzoek vooraf (geschiltype, urgentie, budget), verzamelt noodzakelijke documenten en vult uw agenda met relevante consultaties.",
      ctaText: "Bekijk een juridische demo",
    },
  },
  "beaute-bien-etre": {
    fr: {
      name: "Beauté & Bien-être",
      title: "Agent IA WhatsApp pour la Beauté et le Bien-être",
      metaTitle: "Agent IA WhatsApp Beauté — Réservations soins et fidélisation sans commission",
      metaDescription: "Automatisez les réservations de soins sur WhatsApp. +71% de réservations en ligne, zéro commission Treatwell, 35% de clients fidélisés.",
      subtitle: "Remplissez votre agenda de soins, fidélisez vos clients et encaissez sans payer de commission à Treatwell ou Planity.",
      useCases: ["Réservations de soins 24h/24 sans commission", "Rappels automatiques J-48h avec confirmation", "Programme de fidélité et offres anniversaire personnalisées", "Vente de produits et coffrets en dehors des séances", "Collecte d'avis Google et recommandations"],
      painPoint: "Treatwell et Planity vous coûtent 20-25% par réservation. Vous n'avez pas accès aux données de vos clients. Votre agenda a des trous que personne ne voit.",
      solution: "L'agent prend les réservations directement sur WhatsApp, sans intermédiaire. Vos clients reviennent parce qu'il les relance automatiquement avec des offres personnalisées.",
      ctaText: "Voir une démo beauté",
    },
    en: {
      name: "Beauty & Wellness",
      title: "WhatsApp AI Agent for Beauty and Wellness",
      metaTitle: "WhatsApp AI Agent Beauty — Treatment bookings and loyalty without commission",
      metaDescription: "Automate treatment bookings on WhatsApp. +71% online bookings, zero Treatwell commission, 35% loyal customers.",
      subtitle: "Fill your treatment schedule, build customer loyalty and earn without paying commissions to Treatwell or Vagaro.",
      useCases: ["24/7 commission-free treatment bookings", "Automatic reminders 48h before with confirmation", "Loyalty programme and personalised birthday offers", "Product and gift set sales between sessions", "Google review and referral collection"],
      painPoint: "Treatwell and Vagaro charge 20-25% per booking. You have no access to your clients' data. Your schedule has gaps that nobody sees.",
      solution: "The agent takes bookings directly on WhatsApp, no middleman. Clients return because it automatically follows up with personalised offers.",
      ctaText: "See a beauty demo",
    },
    de: {
      name: "Beauty & Wellness",
      title: "WhatsApp KI-Agent für Beauty und Wellness",
      metaTitle: "WhatsApp KI-Agent Beauty — Behandlungsbuchungen ohne Provision",
      metaDescription: "Automatisieren Sie Behandlungsbuchungen auf WhatsApp. +71% Online-Buchungen, null Treatwell-Provision, 35% treue Kunden.",
      subtitle: "Füllen Sie Ihren Behandlungskalender, bauen Sie Kundentreue auf und verdienen Sie ohne Provisionen.",
      useCases: ["24/7-Behandlungsbuchungen ohne Provision", "Automatische Erinnerungen 48h vorher mit Bestätigung", "Treueprogramm und personalisierte Geburtstagsangebote", "Produkt- und Gutscheinverkäufe zwischen Sitzungen", "Google-Bewertungs- und Empfehlungssammlung"],
      painPoint: "Treatwell berechnet 20-25% pro Buchung. Sie haben keinen Zugang zu Kundendaten. Ihr Kalender hat Lücken, die niemand sieht.",
      solution: "Der Agent nimmt Buchungen direkt auf WhatsApp an, ohne Mittelsmänner. Kunden kommen wieder, weil er automatisch mit personalisierten Angeboten nachfasst.",
      ctaText: "Beauty-Demo ansehen",
    },
    nl: {
      name: "Beauty & Wellness",
      title: "WhatsApp AI-agent voor Beauty en Wellness",
      metaTitle: "WhatsApp AI-agent Beauty — Behandelingsboekingen en loyaliteit zonder commissie",
      metaDescription: "Automatiseer behandelingsboekingen op WhatsApp. +71% online boekingen, nul Treatwell commissie, 35% loyale klanten.",
      subtitle: "Vul uw behandelingsagenda, bouw klantloyaliteit op en verdien zonder commissie te betalen aan Treatwell of Vagaro.",
      useCases: ["24/7 commissievrije behandelingsboekingen", "Automatische herinneringen 48u van tevoren met bevestiging", "Loyaliteitsprogramma en gepersonaliseerde verjaardagsaanbiedingen", "Product- en cadeausetverkoop tussen sessies", "Google-recensie en doorverwijzingsverzameling"],
      painPoint: "Treatwell en Vagaro rekenen 20-25% per boeking. U heeft geen toegang tot uw klantgegevens. Uw agenda heeft gaten die niemand ziet.",
      solution: "De agent neemt boekingen direct aan op WhatsApp, zonder tussenpersoon. Klanten keren terug omdat hij automatisch opvolgt met gepersonaliseerde aanbiedingen.",
      ctaText: "Bekijk een beauty demo",
    },
  },
  logistique: {
    fr: {
      name: "Logistique",
      title: "Agent IA WhatsApp pour la Logistique",
      metaTitle: "Agent IA WhatsApp Logistique — Suivi livraisons et WISMO automatisé",
      metaDescription: "Automatisez le suivi des livraisons sur WhatsApp. Réduisez les appels WISMO de 73%, informez 98% de vos clients proactivement, améliorez votre NPS.",
      subtitle: "Informez vos clients proactivement sur leurs livraisons, gérez les retours automatiquement et éliminez les appels WISMO.",
      useCases: ["Notifications proactives à chaque étape de livraison", "Réponse automatique aux 'où est ma commande ?'", "Gestion des retours et remboursements via WhatsApp", "Collecte de disponibilité pour seconde tentative de livraison", "Escalade automatique vers humain pour litiges complexes"],
      painPoint: "30% de vos appels entrants sont des WISMO. Votre équipe SAV explique inlassablement le même statut. Les clients mécontents laissent des avis négatifs.",
      solution: "L'agent notifie chaque client à chaque étape de la livraison, répond automatiquement aux questions de suivi, et gère les retours sans intervention humaine.",
      ctaText: "Voir une démo logistique",
    },
    en: {
      name: "Logistics",
      title: "WhatsApp AI Agent for Logistics",
      metaTitle: "WhatsApp AI Agent Logistics — Automated delivery tracking and WISMO",
      metaDescription: "Automate delivery tracking on WhatsApp. Reduce WISMO calls by 73%, proactively inform 98% of your customers, improve your NPS.",
      subtitle: "Proactively inform your customers about their deliveries, manage returns automatically and eliminate WISMO calls.",
      useCases: ["Proactive notifications at every delivery stage", "Automatic 'where is my order?' responses", "Returns and refund management via WhatsApp", "Availability collection for second delivery attempts", "Automatic escalation to human for complex disputes"],
      painPoint: "30% of your inbound calls are WISMO. Your customer service team endlessly explains the same status. Unhappy customers leave negative reviews.",
      solution: "The agent notifies each customer at every delivery stage, automatically answers tracking questions, and manages returns without human intervention.",
      ctaText: "See a logistics demo",
    },
    de: {
      name: "Logistik",
      title: "WhatsApp KI-Agent für Logistik",
      metaTitle: "WhatsApp KI-Agent Logistik — Automatisierte Lieferverfolgung und WISMO",
      metaDescription: "Automatisieren Sie die Lieferverfolgung auf WhatsApp. Reduzieren Sie WISMO-Anrufe um 73%, informieren Sie 98% Ihrer Kunden proaktiv.",
      subtitle: "Informieren Sie Ihre Kunden proaktiv über ihre Lieferungen, verwalten Sie Rücksendungen automatisch und eliminieren Sie WISMO-Anrufe.",
      useCases: ["Proaktive Benachrichtigungen bei jedem Lieferschritt", "Automatische Antworten auf 'Wo ist meine Bestellung?'", "Rücksendungs- und Erstattungsmanagement über WhatsApp", "Verfügbarkeitsabfrage für zweite Lieferversuche", "Automatische Eskalation zu Menschen bei komplexen Streitigkeiten"],
      painPoint: "30% Ihrer eingehenden Anrufe sind WISMO. Ihr Kundendienstteam erklärt endlos denselben Status.",
      solution: "Der Agent benachrichtigt jeden Kunden bei jedem Lieferschritt, beantwortet automatisch Tracking-Fragen und verwaltet Rücksendungen ohne menschliches Eingreifen.",
      ctaText: "Logistik-Demo ansehen",
    },
    nl: {
      name: "Logistiek",
      title: "WhatsApp AI-agent voor Logistiek",
      metaTitle: "WhatsApp AI-agent Logistiek — Geautomatiseerde leveringsopvolging en WISMO",
      metaDescription: "Automatiseer leveringsopvolging op WhatsApp. Reduceer WISMO-oproepen met 73%, informeer 98% van uw klanten proactief, verbeter uw NPS.",
      subtitle: "Informeer uw klanten proactief over hun leveringen, beheer retourzendingen automatisch en elimineer WISMO-oproepen.",
      useCases: ["Proactieve meldingen bij elke leveringsfase", "Automatische antwoorden op 'waar is mijn bestelling?'", "Retour- en terugbetalingsbeheer via WhatsApp", "Beschikbaarheidsverzameling voor tweede bezorgpogingen", "Automatische escalatie naar medewerker voor complexe geschillen"],
      painPoint: "30% van uw inkomende oproepen zijn WISMO. Uw klantenserviceteam legt eindeloos dezelfde status uit. Ontevreden klanten laten negatieve recensies achter.",
      solution: "De agent informeert elke klant bij elke leveringsfase, beantwoordt automatisch trackingvragen en beheert retourzendingen zonder menselijke tussenkomst.",
      ctaText: "Bekijk een logistiek demo",
    },
  },
  "saas-tech": {
    fr: {
      name: "SaaS & Tech",
      title: "Agent IA WhatsApp pour les SaaS et Entreprises Tech",
      metaTitle: "Agent IA WhatsApp SaaS — Onboarding, support et upsell automatisés",
      metaDescription: "Automatisez l'onboarding SaaS et le support L1 sur WhatsApp. -58% de tickets support, +34% de taux d'activation, CSAT 4.6/5.",
      subtitle: "Activez vos nouveaux utilisateurs, automatisez le support de premier niveau et identifiez les opportunités d'upsell — sans agrandir votre équipe.",
      useCases: ["Onboarding guidé pas-à-pas pour les nouveaux utilisateurs", "Support L1 automatique (FAQ, bugs connus, procédures)", "Détection des signaux churn et relance proactive", "Campagnes d'upsell ciblées au bon moment du parcours", "Collecte de feedback produit et NPS automatisés"],
      painPoint: "60% de vos nouveaux utilisateurs n'activent pas le produit. Votre équipe support répond aux mêmes 20 questions en boucle. Le churn est invisible jusqu'à la facture.",
      solution: "L'agent guide chaque utilisateur dans l'activation, répond aux questions techniques de niveau 1, et détecte les signaux de churn 30 jours avant l'échéance pour déclencher une intervention.",
      ctaText: "Voir une démo SaaS",
    },
    en: {
      name: "SaaS & Tech",
      title: "WhatsApp AI Agent for SaaS and Tech Companies",
      metaTitle: "WhatsApp AI Agent SaaS — Automated onboarding, support and upsell",
      metaDescription: "Automate SaaS onboarding and L1 support on WhatsApp. -58% support tickets, +34% activation rate, 4.6/5 CSAT.",
      subtitle: "Activate new users, automate first-level support and identify upsell opportunities — without growing your team.",
      useCases: ["Step-by-step guided onboarding for new users", "Automatic L1 support (FAQ, known bugs, procedures)", "Churn signal detection and proactive re-engagement", "Targeted upsell campaigns at the right moment in the journey", "Automated product feedback and NPS collection"],
      painPoint: "60% of your new users never activate the product. Your support team answers the same 20 questions on repeat. Churn is invisible until the invoice.",
      solution: "The agent guides each user through activation, handles level-1 technical questions, and detects churn signals 30 days before renewal to trigger intervention.",
      ctaText: "See a SaaS demo",
    },
    de: {
      name: "SaaS & Tech",
      title: "WhatsApp KI-Agent für SaaS und Tech-Unternehmen",
      metaTitle: "WhatsApp KI-Agent SaaS — Automatisiertes Onboarding, Support und Upsell",
      metaDescription: "Automatisieren Sie SaaS-Onboarding und L1-Support auf WhatsApp. -58% Support-Tickets, +34% Aktivierungsrate, 4,6/5 CSAT.",
      subtitle: "Aktivieren Sie neue Nutzer, automatisieren Sie den Erstlevel-Support und identifizieren Sie Upsell-Möglichkeiten — ohne Ihr Team zu vergrößern.",
      useCases: ["Schritt-für-Schritt-Onboarding für neue Nutzer", "Automatischer L1-Support (FAQ, bekannte Bugs, Verfahren)", "Churn-Signalerkennnung und proaktives Re-Engagement", "Gezielte Upsell-Kampagnen zum richtigen Zeitpunkt", "Automatisierte Produktfeedback- und NPS-Sammlung"],
      painPoint: "60% Ihrer neuen Nutzer aktivieren das Produkt nicht. Ihr Support-Team beantwortet endlos dieselben 20 Fragen. Churn ist unsichtbar bis zur Rechnung.",
      solution: "Der Agent führt jeden Nutzer durch die Aktivierung, bearbeitet technische Fragen der Stufe 1 und erkennt Churn-Signale 30 Tage vor Verlängerung.",
      ctaText: "SaaS-Demo ansehen",
    },
    nl: {
      name: "SaaS & Tech",
      title: "WhatsApp AI-agent voor SaaS en Tech-bedrijven",
      metaTitle: "WhatsApp AI-agent SaaS — Geautomatiseerde onboarding, support en upsell",
      metaDescription: "Automatiseer SaaS onboarding en L1-support op WhatsApp. -58% supporttickets, +34% activeringspercentage, 4,6/5 CSAT.",
      subtitle: "Activeer nieuwe gebruikers, automatiseer eerste niveau support en identificeer upsell kansen — zonder uw team te laten groeien.",
      useCases: ["Stap-voor-stap begeleide onboarding voor nieuwe gebruikers", "Automatische L1-support (FAQ, bekende bugs, procedures)", "Churnssignaaldetectie en proactieve heractivering", "Gerichte upsell campagnes op het juiste moment in het traject", "Geautomatiseerde productfeedback en NPS-verzameling"],
      painPoint: "60% van uw nieuwe gebruikers activeert het product niet. Uw supportteam beantwoordt eindeloos dezelfde 20 vragen. Churn is onzichtbaar tot de factuur.",
      solution: "De agent begeleidt elke gebruiker door de activering, verwerkt technische vragen van niveau 1 en detecteert churnsignalen 30 dagen voor verlenging om een interventie te starten.",
      ctaText: "Bekijk een SaaS demo",
    },
  },
};

export function getSecteur(slug: string): Secteur | undefined {
  return SECTEURS.find((s) => s.slug === slug);
}

export function getSecteurTranslation(slug: string, locale: string): SecteurTranslation | undefined {
  return SECTEUR_TRANSLATIONS[slug]?.[locale] ?? SECTEUR_TRANSLATIONS[slug]?.["fr"];
}
